### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../results/0512_223411.txt'

### ISSUE THREAD

**Issue by GitYesm** [haiciyang/Feature-predictor-for-speech-codec#2]

**Comment by GitYesm** [comment]
In the LibriSpeech dataset, the audio is .flac, why is your dataset_orig.py  is  .wav? If you do some processing, I think you should write it down in ReadMe. Although I am interested in that work

**Comment by haiciyang** [comment]
Hello, thank you for your suggestions. You need to convert all the *.flac to *.wav. I don't remember the exact tools I used,  but here are some potential ways that I can find at this moment. https://stackoverflow.com/questions/58424108/with-python-how-can-i-convert-a-flac-stream-to-a-wav-stream
I hope this helps you.

**Comment by GitYesm** [comment]
> Hello, thank you for your suggestions. You need to convert all the *.flac to *.wav. I don't remember the exact tools I used, but here are some potential ways that I can find at this moment. https://stackoverflow.com/questions/58424108/with-python-how-can-i-convert-a-flac-stream-to-a-wav-stream I hope this helps you.

thanks，look forward to your  future work !
